from __future__ import annotations

BLOCKING_EXTRACTION_ISSUES = {
    "LLM_INVALID_RESPONSE_FORMAT",
    "FUND_DISCOVERY_EMPTY",
    "TRANSACTION_SLOT_EMPTY",
    "TRANSFER_AMOUNT_EMPTY",
    "SETTLE_CLASS_EMPTY",
    "FUND_METADATA_INCOMPLETE",
    "TRANSFER_AMOUNT_MISSING",
    "TRANSFER_AMOUNT_CONFLICT",
    "SETTLE_CLASS_MISSING",
    "ORDER_TYPE_MISSING",
    "T_DAY_MISSING",
    "BASE_DATE_STAGE_PARTIAL",
    "T_DAY_STAGE_PARTIAL",
    "TRANSFER_AMOUNT_STAGE_PARTIAL",
    "SETTLE_CLASS_STAGE_PARTIAL",
    "ORDER_TYPE_STAGE_PARTIAL",
}

SOFT_COVERAGE_WARNING = "ORDER_COVERAGE_ESTIMATE_MISMATCH"
VA_LLM_TEMPERATURE = 0.0
VA_LLM_MAX_TOKENS = 16384
VA_LLM_TIMEOUT_SECONDS = 120
VA_LLM_STAGE_BATCH_SIZE = 12
VA_LLM_RETRY_ATTEMPTS = 3
VA_LLM_RETRY_BACKOFF_SECONDS = 1.5
VA_LLM_CHUNK_SIZE_CHARS = 12000
INSTRUCTION_DOCUMENT_STAGE_ISSUE_RETRY_ATTEMPTS = 1
OTHER_STAGE_ISSUE_RETRY_ATTEMPTS = 2
MAX_PARALLEL_LLM_BATCH_WORKERS = 1
STAGE_SPECIFIC_MAX_TOKENS: dict[str, int] = {
    "instruction_document": 4096,
    "base_date": 4096,
    "settle_class": 8192,
    "order_type": 4096,
}
T_DAY_STAGE_BATCH_SIZE = 6
INTERNAL_RETRY_FINDING_PREFIX = "_RETRY_"
REASON_SUMMARY_MAX_CHARS = 160
STAGE_ITEM_METADATA_FIELDS = frozenset({"reason_code"})
STAGE_RESULT_METADATA_FIELDS = frozenset({"reason_summary"})
INSTRUCTION_DOCUMENT_REASON_CODES = frozenset(
    {
        "INSTR_ORDER_ROWS_PRESENT",
        "INSTR_NET_OR_SCHEDULE_PRESENT",
        "INSTR_OUTFLOW_AMOUNT_PRESENT",
        "NONINSTR_COVER_EMAIL",
        "NONINSTR_ATTACHMENT_WRAPPER",
        "NONINSTR_NO_ACTIONABLE_ROWS",
        "NONINSTR_APPROVAL_NOTICE",
    }
)
FUND_INVENTORY_REASON_CODES = frozenset(
    {
        "FUND_MANAGER_SCOPED",
        "FUND_NO_MANAGER_SCOPE",
        "FUND_NET_AMOUNT_ROW",
        "FUND_EXPLICIT_SUB_ROW",
        "FUND_EXPLICIT_RED_ROW",
        "FUND_CODE_ONLY_ROW",
        "FUND_OTHER_VERIFIED",
    }
)
BASE_DATE_REASON_CODES = frozenset(
    {
        "DATE_DOC_HEADER",
        "DATE_GRID_ALIGNED",
        "DATE_SETTLEMENT_LABEL",
        "DATE_SECTION_ROW",
        "DATE_EMAIL_FALLBACK",
        "DATE_OTHER_VERIFIED",
    }
)
T_DAY_REASON_CODES = frozenset(
    {
        "SLOT_T0_NET",
        "SLOT_T0_EXPLICIT_SUB",
        "SLOT_T0_EXPLICIT_RED",
        "SLOT_TPLUS_SCHEDULE",
        "SLOT_BUSINESS_DAY_HEADER",
        "SLOT_SECTION_DIRECTION",
        "SLOT_OTHER_VERIFIED",
    }
)
TRANSFER_AMOUNT_REASON_CODES = frozenset(
    {
        "AMOUNT_NET_COLUMN",
        "AMOUNT_EXPLICIT_SUB",
        "AMOUNT_EXPLICIT_RED",
        "AMOUNT_SCHEDULE_BUCKET",
        "AMOUNT_SIGNED_OUTFLOW",
        "AMOUNT_OTHER_VERIFIED",
    }
)
SETTLE_CLASS_REASON_CODES = frozenset(
    {
        "SETTLE_SAME_DAY_LABEL",
        "SETTLE_FUTURE_LABEL",
        "SETTLE_BUSINESS_DAY_HEADER",
        "SETTLE_PROCESSED_RESULT",
        "SETTLE_TDAY_FALLBACK",
        "SETTLE_OTHER_VERIFIED",
    }
)
ORDER_TYPE_REASON_CODES = frozenset(
    {
        "ORDER_SIGN_POSITIVE",
        "ORDER_SIGN_NEGATIVE",
        "ORDER_LABEL_SUB",
        "ORDER_LABEL_RED",
        "ORDER_SECTION_SUB",
        "ORDER_SECTION_RED",
        "ORDER_TRANSACTION_TYPE",
        "ORDER_OTHER_VERIFIED",
    }
)
